refactor: publish-copy & publish-odr TDE-868
linz/topo-workflows pull request #173
Opened 2023-09-12 04:04 UTC by MDavidson17

**Why:**
Currently the two workflows: `publish-odr` and `publish-copy` are almost direct copies of each other with a lot of duplicate code. This is a risk for future work as the same code will need to be updated in two different places, and it is likely to be forgotten/mistakes made. 

**Description:**
`copy`, `create-manifest` and `publish-to-github` have been pulled out into template workflow-templates that are each called by the tasks in `publish-copy` and `publish-odr`

The alternative option is to remove `publish-odr` and add it as options/parameters to `publish-copy`. I didn't do this as we had discussed wanting to make sure the odr was separate and the future possible enhancements of approval steps / restricting users who can run the workflow.

2023-09-12 04:04 UTC, MDavidson17 commented on templates/argo-tasks/copy.yml
> +  name: tpl-copy
nb: the tpl- workflow-templates had to be created for github actions to pass, do they be removed before this PR is merged?

2023-09-13 22:22 UTC, amfage commented on templates/argo-tasks/copy.yml
> +  name: tpl-copy
You don't need to remove them. They will be overwritten.

2023-09-17 20:21 UTC, paulfouquet requested changes

2023-09-17 20:21 UTC, paulfouquet commented on templates/argo-tasks/copy.yml
> +            default: "s3://linz-bucket-config/config-write.imagery.json,s3://linz-bucket-config/config-write.elevation.json,s3://linz-bucket-config/config-write.topographic.json,s3://linz-bucket-conf
I think `s3://linz-bucket-config/config.json` should be a persistent value and the other additional roles concatenated with it. (see suggestion line 46)

2023-09-17 20:21 UTC, paulfouquet commented on templates/argo-tasks/copy.yml
> +            value: "{{inputs.parameters.aws-role-config-path}}"
```suggestion
            value: "s3://linz-bucket-config/config.json,{{inputs.parameters.aws-role-config-path}}"
```

2023-09-17 20:21 UTC, paulfouquet commented on templates/argo-tasks/copy.yml
> +            value: "{{inputs.parameters.aws-role-config-path}}"
⬆️  will allow to remove `s3://linz-bucket-config/config.json` from the additional roles in `aws-role-config-path` parameter

2023-09-17 20:21 UTC, paulfouquet commented on templates/argo-tasks/README.md
> +Create a manifest file for a user specificed source and target that includes `.tiff`, `.json`, and `.tfw` files from the source.
I think that is a copy-paste from the description above.

2023-09-17 20:21 UTC, paulfouquet commented on templates/argo-tasks/push-to-github.yml
> +            description: location of data to publish
```suggestion
            description: location where the source collection.json file is
```

2023-09-17 20:21 UTC, paulfouquet commented on templates/argo-tasks/push-to-github.yml
> +            description: location to publish data to
```suggestion
            description: location where the destination collection.json file will be
```

2023-09-22 01:51 UTC, blacha approved these changes

2023-09-22 02:10 UTC, amfage commented on templates/argo-tasks/README.md
> +Create a manifest file for a user specificed source and target that includes `.tiff`, `.json`, and `.tfw` files from the source.
```suggestion
Create a manifest file for a user specified source and target that includes `.tiff`, `.json`, and `.tfw` files from the source.
```

2023-09-22 02:12 UTC, amfage commented on templates/argo-tasks/push-to-github.yml
> +            description: Reposistory Name (only used when Identified that push to github is required)
```suggestion
            description: Repository Name (only used when identified that push to GitHub is required)
```

2023-09-25 19:09 UTC, paulfouquet approved these changes

2023-09-26 00:22 UTC, amfage approved these changes

2023-09-26 00:24 UTC, merged