feat: Label workflows TDE-843
linz/topo-workflows pull request #299
Opened 2023-11-21 21:18 UTC by l0b0

#### Motivation

Enable Argo users to filter workflow runs easily.

#### Checklist

- [ ] Tests updated (not sure if any are needed)
- [ ] Docs updated
- [x] Issue linked in Title

2023-11-21 21:23 UTC, l0b0 commented on workflows/imagery/ascii-standardise-publish.yaml
> +    linz.govt.nz/category: raster
This is still unclear what would be a good value here. The directory name is "imagery", the ticket (I think) says to use "raster", but if I understand correctly neither are accurate since these workflows also process vector data.

2023-11-22 00:58 UTC, dwsilk requested changes

2023-11-22 00:58 UTC, dwsilk commented on workflows/imagery/publish-copy.yaml
> +    linz.govt.nz/data-sub-type: elevation
remove the `data-sub-type`

2023-11-22 00:58 UTC, dwsilk commented on workflows/imagery/ascii-standardise-publish.yaml
> +    linz.govt.nz/category: raster
I tihnk `raster` is accurate but can we also change the directory name to `raster`. Any side effects from that?

2023-11-22 01:43 UTC, l0b0 commented on workflows/imagery/ascii-standardise-publish.yaml
> +    linz.govt.nz/category: raster
I've pulled out the [directory rename](https://github.com/linz/topo-workflows/pull/300).

2023-11-22 02:06 UTC, l0b0 commented on workflows/imagery/publish-copy.yaml
> +    linz.govt.nz/data-sub-type: elevation
Should I remove `linz.govt.nz/data-sub-type: maps` as well?

2023-11-23 19:11 UTC, dwsilk commented on workflows/imagery/publish-copy.yaml
> +    linz.govt.nz/data-sub-type: elevation
No, keeping that one is fine. It just can't be added here by default as `publish-copy` is not always used for `elevation`.

2023-11-23 19:23 UTC, dwsilk requested changes

2023-11-23 19:23 UTC, dwsilk commented on workflows/raster/ascii-standardise-publish.yaml
> +    linz.govt.nz/category: raster
add `linz.govt.nz/data-type: raster` and `linz.govt.nz/data-sub-type: elevation`

2023-11-23 19:23 UTC, dwsilk commented on workflows/basemaps/create-overview.yaml
> +    linz.govt.nz/category: basemaps
add `linz.govt.nz/data-type: raster`

2023-11-23 19:23 UTC, dwsilk commented on workflows/basemaps/imagery-import-cogify.yml
> +    linz.govt.nz/category: basemaps
add `linz.govt.nz/data-type: raster`

2023-11-23 19:23 UTC, dwsilk commented on workflows/basemaps/imagery-import.yaml
> +    linz.govt.nz/category: basemaps
add `linz.govt.nz/data-type: raster`

2023-11-23 19:23 UTC, dwsilk commented on workflows/basemaps/mapsheet-json.yaml
> +    linz.govt.nz/category: basemaps
add `linz.govt.nz/data-type: raster` and `linz.govt.nz/data-sub-type: maps` and `linz.govt.nz/data-sub-type: imagery`

2023-11-23 19:23 UTC, dwsilk commented on workflows/basemaps/create-overview-all.yaml
> +    linz.govt.nz/category: basemaps
add `linz.govt.nz/data-type: raster`

2023-11-23 19:23 UTC, dwsilk commented on workflows/raster/publish-odr.yaml
> +    linz.govt.nz/category: raster
add `linz.govt.nz/data-type: raster`

2023-11-23 19:23 UTC, dwsilk commented on workflows/raster/standardising-publish-import.yaml
> +    linz.govt.nz/category: raster
add `linz.govt.nz/data-type: raster`

2023-11-23 19:23 UTC, dwsilk commented on workflows/raster/standardising.yaml
> +    linz.govt.nz/category: raster
add `linz.govt.nz/data-type: raster`

2023-11-23 19:55 UTC, l0b0 commented on workflows/basemaps/mapsheet-json.yaml
> +    linz.govt.nz/category: basemaps
I don't think I can have two `linz.govt.nz/data-sub-type` labels.

2023-11-23 20:23 UTC, dwsilk commented on workflows/basemaps/mapsheet-json.yaml
> +    linz.govt.nz/category: basemaps
In that case, `linz.govt.nz/data-sub-type: maps` only.

2023-11-24 00:50 UTC, dwsilk approved these changes

2023-11-26 21:27 UTC, paulfouquet commented on workflows/raster/tests.yaml
> +    linz.govt.nz/data-type: raster
Do we want to add a `data-type` on a test? would that not pollute the filter results?

Also, while this test uses `topo-imagery` container, the code submitted could be not raster related.

2023-11-27 20:19 UTC, merged