fix: create-thumbnails workflow should not try publishing data TDE-969
linz/topo-workflows pull request #319
Opened 2023-11-30 20:46 UTC by paulfouquet

#### Motivation

`create-thumbnails` workflow should only create the thumbnails in a "temporary" place in the s3 `scratch` bucket. The files have to be verified before copied over their final destination.

#### Modification

The WorkflowTemplate was containing publish copy tasks that should not be done part of this workflow. Instead, a separate workflow to copy files (`publish-copy`) should be run after someone verified the files.

#### Checklist

_If not applicable, provide explanation of why._

- [ ] Tests updated - N/A
- [x] Docs updated
- [x] Issue linked in Title

2023-11-30 20:48 UTC, dwsilk requested changes

2023-11-30 20:48 UTC, dwsilk commented on workflows/util/README.md
> +| target    | str   | s3://linz-                        | the target uri (path) to copy the input and thumbnails                                          |
take out `target` from here?

2023-11-30 21:47 UTC, dwsilk requested changes

2023-11-30 21:47 UTC, dwsilk commented on workflows/util/README.md
> +| include   | regex | .\*.\*.tif?$                      | A regular expression to match object path(s) or name(s) from within the source path to include. |
```suggestion
| include   | regex | .\*.tiff?$                      | A regular expression to match object path(s) or name(s) from within the source path to include. |
```

2023-11-30 21:47 UTC, dwsilk commented on workflows/util/create-thumbnails.yaml
>          value: '.*.*.tif?$'
```suggestion
        value: '.*.tiff?$'
```

2023-11-30 21:48 UTC, dwsilk requested changes

2023-11-30 21:48 UTC, dwsilk commented on workflows/util/README.md
> +| include   | regex | .\*.\*.tif?$                      | A regular expression to match object path(s) or name(s) from within the source path to include. |
```suggestion
| include   | regex | .\*.tiff?$                      | A regular expression to match object path(s) or name(s) from within the source path to include.   |
```

2023-11-30 22:22 UTC, amfage approved these changes

2023-11-30 22:25 UTC, merged

2023-12-01 00:17 UTC, l0b0 commented on workflows/util/README.md
> +| include   | regex | .\*.\*.tif?$                      | A regular expression to match object path(s) or name(s) from within the source path to include. |
Filed [ticket](https://toitutewhenua.atlassian.net/browse/TDE-970).