feat(basemaps): Another cron vector etl workflow for 53382-nz-roads-addressing layer.
linz/topo-workflows pull request #493
Opened 2024-03-21 01:02 UTC by Wentao-Kuang

#### Motivation

We need a new cron workflow to process the nz road addressing layer into basemaps

#### Modification

- Update the ETL workflow to take filename parameter
- new cron workflow to process road addressing layer

#### Checklist

_If not applicable, provide explanation of why._

- [ ] Tests updated
- [ ] Docs updated
- [ ] Issue linked in Title

2024-03-24 22:15 UTC, l0b0 reviewed
LGTM, just wondering about the checklist contents.

2024-03-24 22:17 UTC, Wentao-Kuang commented
> LGTM, just wondering about the checklist contents.

Good point, it mostly just reminders for update related stuff. I just forget to add the Jira ticket in the Titile.

2024-03-24 23:14 UTC, blacha approved these changes

2024-03-25 01:27 UTC, l0b0 requested changes
> If not applicable, provide explanation of why.

2024-03-25 01:58 UTC, l0b0 approved these changes

2024-03-25 01:59 UTC, merged