feat: imagery workflows README.md TDE-571 & TDE-575
linz/topo-workflows pull request #63
Opened 2022-11-22 04:00 UTC by MDavidson17

2022-11-22 22:11 UTC, paulfouquet submitted a review, later dismissed

2022-11-24 02:42 UTC, dwsilk requested changes

2022-11-24 02:42 UTC, dwsilk commented on workflows/imagery/README.md
> +This workflow processes raw tiff files for the Topo Data Publishing Team (TDP).
This workflow processes supplied Aerial Imagery TIFF files into consistent Cloud Optimised GeoTIFFs with STAC metadata.

2022-11-24 02:42 UTC, dwsilk commented on workflows/imagery/README.md
> +Gdal_translate, non-visual qa, STAC creation, and STAC validation are all steps included within this workflow.
Standardisation using gdal-translate, non-visual QA, STAC creation...

2022-11-24 02:42 UTC, dwsilk commented on workflows/imagery/README.md
> +| description    | str   | \*Region\* \*Scale\* \*Urban/Rural\* Aerial Photos | Collection description
Description should be

> Orthophotography within the \*Region Name\* region captured in the \*Year\*-\*Year\* flying season.

Doesn't add any more information than the title, it's just the standard first line from our LDS abstracts, which will do as a placeholder for now.

2022-11-24 02:42 UTC, dwsilk commented on workflows/imagery/README.md
> +| title          | str   | \*Region\* \*Scale\* Aerial Photos (\*year/s\*)    | Collection title
Title should be

> \*Region/District/City\* \*GSD\* \*Urban/Rural\* Aerial Photos (\*Year-Year\*)

2022-11-24 02:42 UTC, dwsilk commented on workflows/imagery/README.md
> +| include        | regex | .tiff?$                                            | The file types from within the source path to include in standardising
This could be used for more than file types, right? It's including any object path / object name that matches the regex?

2022-11-24 02:42 UTC, dwsilk commented on workflows/imagery/README.md
> +The follow steps have been grouped together into standardise-validate.
follow -> following

2022-11-24 02:42 UTC, dwsilk commented on workflows/imagery/README.md
> +- from `linz-imagery-uploads` to `linz-imagery-staging` to store a copy of the uploaded RGBI imagery.
`linz-imagery-uploads` -> `linz-imagery-upload`

2022-11-24 02:42 UTC, dwsilk commented on workflows/imagery/README.md
> +| include     | regex | .tiff?\$\|.json\$\|.tfw\$                     | The file types from within the source path to include in the copy.
could be adjusted for purposes other than file types?

2022-11-24 20:01 UTC, dwsilk requested changes

2022-11-24 20:01 UTC, dwsilk commented on workflows/imagery/README.md
> +This step runs `no data`, `band count`, `colour interpretation`, and `srs` non visual QA checks.
Can we add more info on exactly what checks currently occur in this step?

2022-11-24 20:01 UTC, dwsilk commented on workflows/imagery/README.md
> +#### Standardise
Does it make sense to link each of these subheadings to the relevant code as well?

2022-11-27 20:42 UTC, dwsilk approved these changes

2022-11-27 20:49 UTC, merged