Feat: test workflow documentation TDE-537
linz/topo-workflows pull request #64
Opened 2022-11-24 22:44 UTC by MDavidson17

2022-11-27 20:32 UTC, paulfouquet commented on workflows/imagery/README.md
> +Paste/write your code at line 22 in the workflow.
Maybe don't specify a line number so we don't have to update that if the workflow file change? I think there is a comment that tells you where to put the code. You can mention that?

2022-11-27 20:32 UTC, paulfouquet commented on workflows/imagery/README.md
> +**In The Argo UI:**
We don't have a generic readme file for these instructions? it looks like it should be re-used somewhere else.

2022-11-28 22:09 UTC, amfage commented on workflows/imagery/README.md
> +The tests workflow has been created so that python code and topo-imagery scripts can be tested in argo.
NIT: it would be nice to capitalise Python and Argo

2022-11-28 22:11 UTC, amfage commented on README.md
> +&emsp; &emsp; &emsp; &rarr; Create
This looks strange in the Github web interface, perhaps it's lost linebreaks?
![Screenshot from 2022-11-29 11-10-13](https://user-images.githubusercontent.com/21299036/204391710-76b19898-676a-435d-8b18-b2e202773831.png)

2022-11-28 23:09 UTC, dwsilk requested changes

2022-11-28 23:09 UTC, dwsilk commented on README.md
> +In the **Workflows** page: <br>
Let's just use a numbered list for this?

2022-11-28 23:10 UTC, amfage approved these changes

2022-11-28 23:29 UTC, dwsilk approved these changes

2022-11-28 23:30 UTC, merged