fix: headings
linz/topo-workflows pull request #65
Opened 2022-11-29 21:55 UTC by MDavidson17

2022-12-04 20:20 UTC, blacha submitted a review, later dismissed

2022-12-05 01:01 UTC, dwsilk requested changes

2022-12-05 01:01 UTC, dwsilk commented on README.md
> +Elastic search is an analytics engine, it allows us to store, search and analyse AWS logs. <br>
Remove the `<br>` tag (and another one below)

2022-12-05 20:06 UTC, dwsilk commented on README.md
> +_All Logs for a pod:_
oh I think you just put two spaces at the end of a line if you want it to linebreak in Markdown, instead of the <br> tag

2022-12-05 20:58 UTC, paulfouquet submitted a review, later dismissed

2022-12-05 21:43 UTC, amfage commented on README.md
>  Once the cluster connection is setup a job can be sumbitted with the cli or accessed via the running argo-server
```suggestion
Once the cluster connection is setup a job can be submitted with the cli or accessed via the running argo-server
```

2022-12-05 22:19 UTC, dwsilk approved these changes

2022-12-05 22:20 UTC, merged