feat: add provider parameter TDE-623
linz/topo-workflows pull request #97
Opened 2023-02-10 03:25 UTC by paulfouquet

https://github.com/linz/topo-imagery/pull/348

2023-02-12 20:32 UTC, dwsilk requested changes

2023-02-12 20:32 UTC, dwsilk commented on workflows/imagery/standardising.yaml
> +            "Taupo District Council",
```suggestion
            "Taupō District Council",
```

2023-02-12 20:32 UTC, dwsilk commented on workflows/imagery/standardising.yaml
> +        value: "AAM NZ"
```suggestion
        value: "Unknown"
```
Let's add an Unknown to the enum and make that the default

2023-02-12 20:32 UTC, dwsilk commented on workflows/imagery/standardising.yaml
> +        value: "Ashburton District Council"
Ditto with an Unknown here too

2023-02-12 21:24 UTC, amfage commented on workflows/imagery/standardising.yaml
> -            memory: 7.8Gi
The memory request should be retained.

2023-02-12 21:26 UTC, paulfouquet commented on workflows/imagery/standardising.yaml
> -            memory: 7.8Gi
merging issue!

2023-02-13 00:26 UTC, rclarkelinz commented on workflows/imagery/standardising.yaml
> +            "NZ Aerial Mapping",
```suggestion
            "NZ Aerial Mapping",
            "Recon Limited",
```

2023-02-13 01:04 UTC, dwsilk requested changes

2023-02-13 01:04 UTC, dwsilk commented on workflows/imagery/standardising.yaml
> +            "NZ Aerial Mapping Ltd",
```suggestion
            "NZ Aerial Mapping",
```

2023-02-13 01:04 UTC, dwsilk commented on workflows/imagery/standardising.yaml
> +            "Sinergise Ltd",
```suggestion
            "Sinergise",
```

2023-02-13 01:04 UTC, dwsilk commented on workflows/imagery/standardising.yaml
> +            "Terralink International Ltd",
```suggestion
            "Terralink International",
```

2023-02-13 02:28 UTC, rclarkelinz approved these changes

2023-02-13 20:00 UTC, dwsilk approved these changes

2023-02-13 20:05 UTC, amfage approved these changes

2023-02-13 20:05 UTC, merged